import type { Factory } from "./types";

/**
 * Static catalog of factories taken from the dashboard screenshot.
 * Each entry is a unique site_id; in production this would come from
 * `getReportFactories` in apps/buildai-dashboard/src/lib/api/server-api.ts.
 */
export const FACTORIES: Factory[] = [
  {
    site_id: "fac-cheer-sagar-3",
    recording_name: "Cheer Sagar Export 3",
    team: "Zelantrix",
    partner_org: "Cheer Sagar",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 243,
  },
  {
    site_id: "fac-cheer-sagar-2",
    recording_name: "Cheer Sagar Export-2",
    team: "Zelantrix",
    partner_org: "Cheer Sagar",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 198,
  },
  {
    site_id: "fac-igc",
    recording_name: "IGC",
    team: "Zelantrix",
    partner_org: "IGC Industries",
    industry: "Manufacturing",
    shift_hours: 10,
    worker_count: 14,
  },
  {
    site_id: "fac-infant-days-7",
    recording_name: "INFANT DAYS-7",
    team: "Zelantrix",
    partner_org: "Infant Group",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 276,
  },
  {
    site_id: "fac-mlc-floor",
    recording_name: "MLC_FLOOR",
    team: "Zelantrix",
    partner_org: "MLC",
    industry: "Manufacturing",
    shift_hours: 10,
    worker_count: 137,
  },
  {
    site_id: "fac-nandhini-food",
    recording_name: "NANDHINI DAIRY (FOOD BLOCK)",
    team: "Zelantrix",
    partner_org: "Nandhini Dairy",
    industry: "Food Processing",
    shift_hours: 10,
    worker_count: 187,
  },
  {
    site_id: "fac-nandhini-milk-curd",
    recording_name: "NANDHINI DAIRY (MILK & CURD BLOCK)",
    team: "Zelantrix",
    partner_org: "Nandhini Dairy",
    industry: "Food Processing",
    shift_hours: 10,
    worker_count: 145,
  },
  {
    site_id: "fac-nandhini-trolley",
    recording_name: "NANDHINI DAIRY LTD (TROLLEY SECTION)",
    team: "Zelantrix",
    partner_org: "Nandhini Dairy",
    industry: "Food Processing",
    shift_hours: 10,
    worker_count: 99,
  },
  {
    site_id: "fac-pcu-1-floor-2",
    recording_name: "PUNIT CREATIONS UNIT-1 / FLOOR-2",
    team: "Zelantrix",
    partner_org: "Punit Creations",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 126,
  },
  {
    site_id: "fac-pcu-7-floor-ground",
    recording_name: "PUNIT CREATIONS UNIT-7 / FLOOR-GROUND",
    team: "Zelantrix",
    partner_org: "Punit Creations",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 28,
  },
  {
    site_id: "fac-pcu-8-floor-1",
    recording_name: "PUNIT CREATIONS UNIT-8 / FLOOR-1",
    team: "Zelantrix",
    partner_org: "Punit Creations",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 76,
  },
  {
    site_id: "fac-pcu-1-floor-1",
    recording_name: "PUNIT CREATIONS UNIT-1 / FLOOR-1",
    team: "Zelantrix",
    partner_org: "Punit Creations",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 137,
  },
  {
    site_id: "fac-pcu-1-floor-3",
    recording_name: "PUNIT CREATIONS UNIT-1 / FLOOR-3",
    team: "Zelantrix",
    partner_org: "Punit Creations",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 147,
  },
  {
    site_id: "fac-pcu-1-floor-ground",
    recording_name: "PUNIT CREATIONS UNIT-1 / FLOOR-GROUND",
    team: "Zelantrix",
    partner_org: "Punit Creations",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 85,
  },
  {
    site_id: "fac-pcu-7-floor-1",
    recording_name: "PUNIT CREATIONS UNIT-7 / FLOOR-1",
    team: "Zelantrix",
    partner_org: "Punit Creations",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 48,
  },
  {
    site_id: "fac-pcu-7-floor-2",
    recording_name: "PUNIT CREATIONS UNIT-7 / FLOOR-2",
    team: "Zelantrix",
    partner_org: "Punit Creations",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 363,
  },
  {
    site_id: "fac-pcu-7-floor-3",
    recording_name: "PUNIT CREATIONS UNIT-7 / FLOOR-3",
    team: "Zelantrix",
    partner_org: "Punit Creations",
    industry: "Garments",
    shift_hours: 10,
    worker_count: 70,
  },
];

export function getFactory(siteId: string): Factory | undefined {
  return FACTORIES.find((f) => f.site_id === siteId);
}
